// EventManagementSystem_react/frontend/src/pages/final.jsx
import { useState } from 'react';
import '../css/final.css'; 
import Footer3 from '../components/footer3';

const Final = () => {
    const [isFormSubmitted, setIsFormSubmitted] = useState(false);
    const [formData, setFormData] = useState({
        name: '',
        phone: '',
        location: ''
    });

    const handleChange = (event) => {
        const { name, value } = event.target;
        setFormData({
            ...formData,
            [name]: value,
        });
    };

    const handleSubmit = async (event) => {
        event.preventDefault();

        try {
            const response = await fetch('http://localhost:5000/auth/final', { // Update the URL to your backend endpoint
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(formData),
            });

            if (response.ok) {
                setIsFormSubmitted(true);
            } else {
                console.error('Failed to submit form');
            }
        } catch (error) {
            console.error('Error submitting form:', error);
        }
    };

    return (
        <div className="background-container">
            <div className="topRight">
                <a href="/book">Book</a>
                <a href="/login">Logout</a>
            </div>
            <div className="final">
                <h2>Book Your Events</h2>
                {!isFormSubmitted ? (
                    <form id="booking" onSubmit={handleSubmit}>
                        <div className="form-group">
                            <label htmlFor="name">Name:</label>
                            <input 
                                type="text" 
                                id="name" 
                                name="name" 
                                value={formData.name} 
                                onChange={handleChange} 
                                required 
                            />
                        </div>
                        <div className="form-group">
                            <label htmlFor="phone">Phone Number:</label>
                            <input 
                                type="text" 
                                id="phone" 
                                name="phone" 
                                value={formData.phone} 
                                onChange={handleChange} 
                                required 
                            />
                        </div>
                        <div className="form-group">
                            <label htmlFor="location">Location:</label>
                            <input 
                                type="text" 
                                id="location" 
                                name="location" 
                                value={formData.location} 
                                onChange={handleChange} 
                                required 
                            />
                        </div>
                        <input type="submit" id="Sbtn" value="Book" />
                    </form>
                ) : (
                    <div className="message" id="message">
                        Our Staff will contact You
                    </div>
                )}
            </div>
            <Footer3 />
        </div>
    );
};

export default Final;

// EventManagementSystem_angular/src/app/final/final.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-final',
  templateUrl: './final.component.html',
  styleUrls: ['./final.component.css']
})
export class FinalComponent {
  isFormSubmitted = false;
  formData = {
    name: '',
    phone: '',
    location: ''
  };

  constructor(private http: HttpClient) {}

  handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    const { name, value } = target;
    this.formData = {
      ...this.formData,
      [name]: value
    };
  }

  async handleSubmit(event: Event) {
    event.preventDefault();

    try {
      const response = await this.http.post('http://localhost:7000/auth/final', this.formData).toPromise();
      if (response) {
        this.isFormSubmitted = true;
      } else {
        console.error('Failed to submit form');
      }
    } catch (error) {
      console.error('Error submitting form:', error);
    }
  }
}

<div class="background-container">
  <div class="topRight">
    <a routerLink="/book">Book</a>
    <a routerLink="/login">Logout</a>
  </div>
  <div class="final">
    <h2>Book Your Events</h2>
    <ng-container *ngIf="!isFormSubmitted; else submittedMessage">
      <form id="booking" (submit)="handleSubmit($event)">
        <div class="form-group">
          <label for="name">Name:</label>
          <input
            type="text"
            id="name"
            name="name"
            [(ngModel)]="formData.name"
            required
          />
        </div>
        <div class="form-group">
          <label for="phone">Phone Number:</label>
          <input
            type="text"
            id="phone"
            name="phone"
            [(ngModel)]="formData.phone"
            required
          />
        </div>
        <div class="form-group">
          <label for="location">Location:</label>
          <input
            type="text"
            id="location"
            name="location"
            [(ngModel)]="formData.location"
            required
          />
        </div>
        <input type="submit" id="Sbtn" value="Book" />
      </form>
    </ng-container>
    <ng-template #submittedMessage>
      <div class="message" id="message">
        Our Staff will contact You
      </div>
    </ng-template>
  </div>
</div>
