// EventManagementSystem_angular/src/app/concert/concert.component.ts
import { Component, OnInit, AfterViewInit } from '@angular/core';

@Component({
  selector: 'app-concert',
  templateUrl: './concert.component.html',
  styleUrls: ['./concert.component.css']
})
export class ConcertComponent implements OnInit, AfterViewInit {
  slideIndex: number = 0;

  ngOnInit(): void {
    // Initialization logic if needed
  }

  ngAfterViewInit(): void {
    this.startSlideshow();
  }

  startSlideshow(): void {
    const slides = document.getElementsByClassName('myslide') as HTMLCollectionOf<Element>;
    const maxSlides = slides.length;
    setInterval(() => {
      this.slideIndex = (this.slideIndex + 1) % maxSlides;
      this.updateSlides();
    }, 2000);
  }

  updateSlides(): void {
    const slides = document.getElementsByClassName('myslide') as HTMLCollectionOf<Element>;
    Array.from(slides).forEach((slide, index) => {
      (slide as HTMLElement).style.display = index === this.slideIndex ? 'block' : 'none';
    });
  }
}

<div>
  <div class="topRight">
    <a routerLink="/">Home</a>
    <a routerLink="/book">Book</a>
    <a routerLink="/login">Logout</a>
  </div>
  <div class="top">
    <div class="slide">
      <img class="myslide" src="/assets/c1.jpg" alt="Slide 1" />
      <img class="myslide" src="/assets/c2.jpg" alt="Slide 2" />
      <img class="myslide" src="/assets/c3.jpg" alt="Slide 3" />
      <img class="myslide" src="/assets/c4.jpg" alt="Slide 4" />
      <div class="head">
        <h1 id="ttext">Concert Package</h1>
      </div>
    </div>
  </div>
  <div class="details">
    <div class="pic1">
      <img src="/assets/c5.jpg" alt="Stage" />
    </div>
    <div class="text1">
      <h1>Stage</h1>
    </div>
    <div class="pic2">
      <img src="/assets/c6.jpg" alt="Stadium" />
    </div>
    <div class="text2">
      <h1 id="text2">Stadium</h1>
    </div>
    <div class="pic3">
      <img src="/assets/c7.jpg" alt="Lighting and Smoke" />
    </div>
    <div class="text3">
      <h1 id="context3">Lighting and Smoke</h1>
    </div>
    <div class="pic4">
      <img src="/assets/c8.jpg" alt="Food Stalls" />
    </div>
    <div class="text4">
      <h1 id="context4">Food Stalls</h1>
    </div>
    <div class="button">
      <a routerLink="/final" class="bttn">Book Now</a>
    </div>
  </div>
</div>

// EventManagementSystem_react/frontend/src/pages/concert.jsx
import { useEffect, useState } from 'react';
import '../css/concert.css'; 
import Footer2 from '../components/footer2'; 

const Concert = () => {
    const [slideIndex, setSlideIndex] = useState(0);
    const slides = document.getElementsByClassName("myslide");

    useEffect(() => {
        const maxSlides = slides.length;
        const slideInterval = setInterval(() => {
            setSlideIndex(prevIndex => {
                let newIndex = prevIndex + 1;
                if (newIndex >= maxSlides) {
                    newIndex = 0;
                }
                return newIndex;
            });
        }, 2000);

        return () => clearInterval(slideInterval);
    }, [slides.length]);

    useEffect(() => {
        Array.from(slides).forEach((slide, index) => {
            slide.style.display = index === slideIndex ? 'block' : 'none';
        });
    }, [slideIndex, slides]);

    return (
        <div>
            <div className="topRight">
                <a href="/">Home</a>
                <a href="/book">Book</a>
                <a href="/login">Logout</a>
            </div>
            <div className="top">
                <div className="slide">
                    <img className="myslide" src="/assets/c1.jpg" alt="Slide 1" />
                    <img className="myslide" src="/assets/c2.jpg" alt="Slide 2" />
                    <img className="myslide" src="/assets/c3.jpg" alt="Slide 3" />
                    <img className="myslide" src="/assets/c4.jpg" alt="Slide 4" />
                    <div className="head">
                        <h1 id="ttext">Concert Package</h1>
                    </div>
                </div>
            </div>
            <div className="details">
                <div className="pic1">
                    <img src="/assets/c5.jpg" alt="Stage" />
                </div>
                <div className="text">
                    <h1 id='context1'>Stage</h1>
                </div>
                <div className="pic2">
                    <img src="/assets/c6.jpg" alt="Stadium" />
                </div>
                <div className="text2">
                    <h1 id='text2'>Stadium</h1>
                </div>
                <div className="pic3">
                    <img src="/assets/c7.jpg" alt="Lighting and Smoke" />
                </div>
                <div className="text3">
                    <h1 id='context3'>Lighting and Smoke</h1>
                </div>
                <div className="pic4">
                    <img src="/assets/c8.jpg" alt="Food Stalls" />
                </div>
                <div className="text4">
                    <h1 id='context4'> Food Stalls</h1>
                </div>
                <div className="button">
        <a href="/final" className="bttn">Book Now</a>
    </div>
            </div>
            <Footer2 id="concertFooter" />
        </div>
    );
};

export default Concert;
