// EventManagementSystem_angular/src/app/create-event/create-event.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-create-event',
  templateUrl: './create-event.component.html',
  styleUrls: ['./create-event.component.css']
})
export class CreateEventComponent implements OnInit {
  eventForm!: FormGroup;  // Note the use of '!'
  events: any[] = [];
  message: string = '';

  constructor(private fb: FormBuilder, private http: HttpClient) { }

  ngOnInit(): void {
    this.eventForm = this.fb.group({
      eventDate: ['', Validators.required],
      eventLocation: ['', Validators.required],
      phoneNumber: ['', Validators.required],
      eventType: ['', Validators.required],
      eventDescription: ['', Validators.required]
    });
  }

  handleSubmit(): void {
    if (this.eventForm.valid) {
      this.http.post('http://localhost:7000/auth/CreateEvent', this.eventForm.value)
        .subscribe({
          next: (data: any) => {
            this.message = 'Event created successfully!';
            this.events.push(this.eventForm.value);
            this.eventForm.reset();
          },
          error: (error) => {
            console.error('Error:', error);
            this.message = 'An error occurred while creating the event.';
          }
        });
    }
  }
}

<div class="sidebar">
  <div class="profile">
    <img src="/assets/admin.jpg" alt="Profile" />
    <p>user</p>
  </div>
  <ul>
    <li><a routerLink="/dashboard">Dashboard</a></li>
    <li><a routerLink="/CreateEvent">Create Events</a></li>
    <li><a routerLink="/ShowEvent">Show Events</a></li>
    <li><a routerLink="/book">Book tickets</a></li>
    <li><a routerLink="/login">Logout</a></li>
  </ul>
</div>

<div class="eventcreation">
  <h1 id="cehead">Elegant Edge Events!</h1>
  <div class="event-form-container">
    <div class="event-form-box">
      <h2>Create Event</h2>
      <form [formGroup]="eventForm" (ngSubmit)="handleSubmit()">
        <label for="eventDate">Date:</label>
        <input
          type="date"
          id="eventDate"
          formControlName="eventDate"
        /><br /><br />

        <label for="eventLocation">Location:</label>
        <input
          type="text"
          id="eventLocation"
          formControlName="eventLocation"
        /><br /><br />

        <label for="phoneNumber">Phone Number:</label>
        <input
          type="tel"
          id="phoneNumber"
          formControlName="phoneNumber"
        /><br /><br />

        <label for="eventType">Event Type:</label>
        <input
          type="text"
          id="eventType"
          formControlName="eventType"
        /><br /><br />

        <label for="eventDescription">Event Description:</label>
        <textarea
          id="eventDescription"
          formControlName="eventDescription"
        ></textarea><br /><br />

        <input type="submit" value="Submit" />
        <p *ngIf="message">{{ message }}</p>
      </form>
    </div>
  </div>
</div>

<div class="Table">
  <h1 id="yr">Your Events</h1>
  <div class="EventList">
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>Phone Number</th>
          <th>Event Type</th>
          <th>Event Description</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let event of events">
          <td>{{ event.eventDate }}</td>
          <td>{{ event.eventLocation }}</td>
          <td>{{ event.phoneNumber }}</td>
          <td>{{ event.eventType }}</td>
          <td>{{ event.eventDescription }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// EventManagementSystem_react/frontend/src/pages/CreateEvent.jsx
import { useState } from 'react';
import '../css/CreateEvent.css'; 

const CreateEvent = () => {
  const [formData, setFormData] = useState({
    eventDate: '',
    eventLocation: '',
    phoneNumber: '',
    eventType: '',
    eventDescription: '',
  });

  const [events, setEvents] = useState([]); // Initialize the events state
  const [message, setMessage] = useState('');

  // Handle input change
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch('http://localhost:5000/auth/CreateEvent', { // Update the URL to match your backend
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });

      const data = await response.json();
      if (response.ok) {
        setMessage('Event created successfully!');
        setEvents([...events, formData]); // Add new event to the list
        setFormData({ eventDate: '', eventLocation: '', phoneNumber: '', eventType: '', eventDescription: '' }); // Clear the form
      } else {
        setMessage(`Error: ${data.msg || 'An error occurred'}`);
      }
    } catch (error) {
      console.error('Error:', error);
      setMessage('An error occurred while creating the event.');
    }
  };

  return (
    <div className="dashboard">
      <div className="sidebar">
        <div className="profile">
          <img src="/assets/admin.jpg" alt="Profile" />
          <p>user</p>
        </div>
        <ul>
          <li><a href="/dashboard">Dashboard</a></li>
          <li><a href="/createevent">Create Events</a></li>
          <li><a href="/showevent">Show Events</a></li>
          <li><a href="/book">Book tickets</a></li>
          <li><a href="/login">Logout</a></li>
        </ul>
      </div>
      <div className="eventcreation">
        <h1 id='cehead'>Elegant Edge Events!</h1>
        <div className="event-form-container">
          <div className="event-form-box">
            <h2>Create Event</h2>
            <form onSubmit={handleSubmit}>
              <label htmlFor="eventDate">Date:</label>
              <input
                type="date"
                id="eventDate"
                name="eventDate"
                value={formData.eventDate}
                onChange={handleInputChange}
                required
              /><br /><br />

              <label htmlFor="eventLocation">Location:</label>
              <input
                type="text"
                id="eventLocation"
                name="eventLocation"
                value={formData.eventLocation}
                onChange={handleInputChange}
                required
              /><br /><br />

              <label htmlFor="phoneNumber">Phone Number:</label>
              <input
                type="tel"
                id="phoneNumber"
                name="phoneNumber"
                value={formData.phoneNumber}
                onChange={handleInputChange}
                required
              /><br /><br />

              <label htmlFor="eventType">Event Type:</label>
              <input
                type="text"
                id="eventType"
                name="eventType"
                value={formData.eventType}
                onChange={handleInputChange}
                required
              /><br /><br />

              <label htmlFor="eventDescription">Event Description:</label>
              <textarea
                id="eventDescription"
                name="eventDescription"
                value={formData.eventDescription}
                onChange={handleInputChange}
                required
              ></textarea><br /><br />

              <input type="submit" value="Submit" />
              {message && <center><p>{message}</p></center>}
            </form>
          </div>
        </div>
      </div>
      <div className="Table">
        <h1 id='yr'>Your Events</h1>
        <div className="EventList">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Location</th>
                <th>Phone Number</th>
                <th>Event Type</th>
                <th>Event Description</th>
              </tr>
            </thead>
            <tbody>
              {events.map((event, index) => (
                <tr key={index}>
                  <td>{event.eventDate}</td>
                  <td>{event.eventLocation}</td>
                  <td>{event.phoneNumber}</td>
                  <td>{event.eventType}</td>
                  <td>{event.eventDescription}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <footer2/>
    </div>
  );
};

export default CreateEvent;
``
