// EventManagementSystem_angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm: FormGroup;
  msg: string = '';
  msgType: string = '';

  constructor(private fb: FormBuilder, private http: HttpClient, private router: Router) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]]
    });
  }

  async onSubmit() {
    if (this.loginForm.invalid) {
      return;
    }

    const { email, password } = this.loginForm.value;

    console.log('Submitting:', { email, password });

    try {
      const response = await this.http.post<any>('http://localhost:7000/auth/login', { email, password }).toPromise();
      console.log('Response Data:', response);

      if (response.msg_type === 'success') {
        this.msg = response.msg;
        this.msgType = response.msg_type;
        this.router.navigate(['/dashboard']);
      } else {
        this.msg = response.msg;
        this.msgType = response.msg_type;
      }
    } catch (error) {
      console.error('Error:', error);
      this.msg = 'Internal server error';
      this.msgType = 'error';
    }
  }
}

<div class="auth-background">
  <div class="glass login">
    <h1>Login</h1>
    <p *ngIf="msg" [ngClass]="msgType">{{ msg }}</p>
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <input
        type="email"
        formControlName="email"
        placeholder="Email"
      />
      <input
        type="password"
        formControlName="password"
        placeholder="Password"
      />
      <button type="submit" class="login-btn">Login</button>
      <p>Not a member? <a routerLink="/signup">Signup</a></p>
    </form>
  </div>
</div>

// EventManagementSystem_react/frontend/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom'; 
import '../css/style.css'; 

const Login = () => {
  const [msg, setMsg] = useState('');
  const [msgType, setMsgType] = useState('');
  const navigate = useNavigate(); 

  const handleSubmit = async (event) => {
    event.preventDefault();
    const email = event.target.email.value;
    const password = event.target.password.value;

    console.log('Submitting:', { email, password }); // Debugging line

    try {
      const response = await fetch('http://localhost:5000/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password })
      });

      const data = await response.json();
      console.log('Response Data:', data); // Debugging line

      if (response.ok) {
        setMsg(data.msg);
        setMsgType(data.msg_type);
        navigate('/dashboard'); 
      } else {
        setMsg(data.msg);
        setMsgType(data.msg_type);
      }
    } catch (error) {
      console.error('Error:', error);
      setMsg('Internal server error');
      setMsgType('error');
    }
  };

  return (
    <div className="auth-background">
      <div className="glass login">
        <h1>Login</h1>
        {msg && <p className={msgType}>{msg}</p>}
        <form onSubmit={handleSubmit}>
          <input 
            type="email" 
            name="email" 
            placeholder="Email" 
            required 
          />
          <input 
            type="password" 
            name="password" 
            placeholder="Password" 
            required 
          />
          <button type="submit" className="login-btn">Login</button>
          <p>Not a member? <Link to="/register">Signup</Link></p>
        </form>
      </div>
    </div>
  );
};

export default Login;
