// EventManagementSystem_angular/src/app/show-event/show-event.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-show-event',
  templateUrl: './show-event.component.html',
  styleUrls: ['./show-event.component.css']
})
export class ShowEventComponent implements OnInit {
  events: any[] = [];
  message: string = '';

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchEvents();
  }

  fetchEvents(): void {
    this.http.get('http://localhost:7000/auth/showEvent')
      .subscribe({
        next: (data: any) => {
          this.events = data;
        },
        error: (error) => {
          console.error('Error fetching events:', error);
          this.message = 'An error occurred while fetching events.';
        }
      });
  }
}

<div class="dashboard">
  <div class="sidebar">
    <div class="profile">
      <img src="/assets/admin.jpg" alt="Profile" />
      <p>user</p>
    </div>
    <ul>
      <li><a routerLink="/dashboard">Dashboard</a></li>
      <li><a routerLink="/CreateEvent">Create Events</a></li>
      <li><a routerLink="/ShowEvent">Show Events</a></li>
      <li><a routerLink="/book">Book tickets</a></li>
      <li><a routerLink="/login">Logout</a></li>
    </ul>
  </div>
  <div class="Table">
    <h1 id="yr">Your Events</h1>
    <div class="EventList">
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Location</th>
            <th>Phone Number</th>
            <th>Event Type</th>
            <th>Event Description</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let event of events">
            <td>{{ event.eventDate }}</td>
            <td>{{ event.eventLocation }}</td>
            <td>{{ event.phoneNumber }}</td>
            <td>{{ event.eventType }}</td>
            <td>{{ event.eventDescription }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <footer>
    <p>&copy; 2024 Elegant Edge Events. All rights reserved.</p>
  </footer>
</div>

// EventManagementSystem_react/frontend/src/pages/ShowEvent.jsx
import  { useEffect, useState } from 'react';
import '../css/ShowEvent.css';

const ShowEvent = () => {
  const [events, setEvents] = useState([]);

  // Fetch events from the backend when the component mounts
  useEffect(() => {
    const fetchEvents = async () => {
      try {
        const response = await fetch('http://localhost:5000/auth/ShowEvent');
        if (!response.ok) {
          throw new Error('Failed to fetch events');
        }
        const data = await response.json();
        setEvents(data);
      } catch (error) {
        console.error('Error fetching events:', error);
      }
    };

    fetchEvents();
  }, []);

  return (
    <div className="dashboard">
      <div className="sidebar">
        <div className="profile">
          <img src="/assets/admin.jpg" alt="Profile" />
          <p>user</p>
        </div>
        <ul>
          <li><a href="/dashboard">Dashboard</a></li>
          <li><a href="/CreateEvent">Create Events</a></li>
          <li><a href="/ShowEvent">Show Events</a></li>
          <li><a href="/Book">Book tickets</a></li>
          <li><a href="/login">Logout</a></li>
        </ul>
      </div>
      <div className="Table">
        <h1 id='yr'>Your Events</h1>
        <div className="EventList">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Location</th>
                <th>Phone Number</th>
                <th>Event Type</th>
                <th>Event Description</th>
              </tr>
            </thead>
            <tbody>
              {events.map((event, index) => (
                <tr key={index}>
                  <td>{event.eventDate}</td>
                  <td>{event.eventLocation}</td>
                  <td>{event.phoneNumber}</td>
                  <td>{event.eventType}</td>
                  <td>{event.eventDescription}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <footer>
        <p>&copy; 2024 Elegant Edge Events. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default ShowEvent;
